[tool.poetry]
name = "squarecloud-api"
version = "3.0.2"
description = "SquareCloud API wrapper"
authors = ["Robert Nogueira <robertlucasnogueira@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "3.8.3"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
blue = "^0.9.1"
isort = "^5.12.0"
taskipy = "^1.12.0"
python-dotenv = "^1.0.0"
discord-py = "^2.3.1"
pytest-asyncio = "^0.21.1"


[tool.poetry.group.doc.dependencies]
mkdocs-material = "^9.1.21"
mkdocstrings = "^0.22.0"
mkdocstrings-python = "^1.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
python_path = "tests"
addopts = "--doctest-modules"

[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]
lint = "isort squarecloud && blue --check --diff squarecloud"
pre_test = "task lint"
test = "pytest -s -x --cov=squarecloud -vv"
post_test = "coverage html"